version: '3.4'

services:
  usuariosapp.api:
    image: ${DOCKER_REGISTRY-}usuariosappapi
    build:
      context: .
      dockerfile: UsuariosApp.API/Dockerfile
    depends_on:
      - db
    links:
      - rabbitmq
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "@Coti2023"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
